name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Ping to Render Backend
        run: curl --silent https://operations-research-project.onrender.com || echo "Ping failed"
