services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.api.routes:app"
    envVars:
      - key: FLASK_ENV
        value: production
